### ISSUE TITLE
include profiles for Xamarin.forms

### ISSUE THREAD

**Issue by jeremysimmons** [StephenCleary/PortableLibraryProfiles#1]
per this answer: https://stackoverflow.com/a/31959866/26877

Xamarin.Forms 1.3:
`portable-win+net45+wp80+MonoAndroid10+MonoTouch10`

Xamarin.Forms 1.4
`portable-win+net45+wp80+win81+wpa81+MonoAndroid10+MonoTouch10+Xamarin.iOS10 `

**Comment by StephenCleary** [comment]
Thanks for the issue, Jeremy!

I do not include the `Mono*` and `Xamarin*` NuGet targets in my profile list, for several reasons:

1. They've never been documented.
2. In the past, they've changed without warning.
3. They only exist on your computer if you install additional software (e.g., Xamarin Studio).
4. Xamarin works just fine without them.

Profile 78 and Profile 259 are both included in the table already, just without the Xamarin extensions that don't add any benefit.
